apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: cloudbees-io/ghactions-run-workflow@v2
        name: Run GHA Workflow
        kind: test
        continue-on-error: true
        with:
          token: ${{ secrets.GH_TOKEN }}
          org-name: cloudbees-days
          repo-name: hackers-organized-2
          branch-name: main
          workflow-name: test-and-build-image
          test-type: JUnit
          test-result-location: junit.xml
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        continue-on-error: true
      - name: Run unit tests
        id: RunUnitTest
        kind: test
        uses: docker://node:lts
        run: |
          npm ci
          npm run test:unit
      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: ${{ cloudbees.workspace }}/junit.xml
    environment: ""
